# Site settings
title: yuantc Blog
SEOTitle: yuantc的博客 | yuantc Blog
header-img: img/home-bg.jpg
email: skycnine@163.com
description: "运维开发、Devops | yauntc，Web & Mobile Lover，Front-End Engineer，UX Designer | 这里是 @yuantc的 的个人博客，与你一起发现更大的世界。"
keyword: "linux, shell, python, java, html, javaScript, 个人网站, Lynn"
url: "https://yuantianchi.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
bokeyuan_username:     skychi
zhihu_username:     
github_username:    yuantianchi

#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: hux

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: https://yuantianchi.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，享受生活<br>每一个不成起舞的日子都是对生命的浪费"
sidebar-avatar: /img/avatar-yuantc.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "meetbill",
        href: "http://meetbill.github.io/"
    },{
        title: "姚红",
        href: "https://www.cnblogs.com/yaohong/"
    },{
        title: "sky-chi",
        href: "http://www.cnblogs.com/ytc6"
    }
]
